version: '3.8'

services:
  mysql8:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-jwt-networks

  redis6:
    image: redis:6.2-alpine
    container_name: redis6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - spring-jwt-networks

  spring-boot-jwt:
    container_name: spring-boot-jwt
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file: ./.env
    networks:
      - spring-jwt-networks
    depends_on:
      - mysql8
      - redis6
    restart: always

volumes:
  mysql-data:
  redis-data:

networks:
  spring-jwt-networks:
    driver: bridge